/** SURAT PERJALANAN DINAS (SPD) */
export const definition = {
  id: 'surat-perjalanan-dinas',
  kode: 'SPD',
  nama: 'Surat Perjalanan Dinas',
  kategori: 'Perjalanan Dinas',
  deskripsi: 'Dibuat otomatis dari Surat Perintah — satu SPD per pegawai yang ditugaskan. Berisi rincian perjalanan masing-masing pegawai.',
  icon: '✈️',
  warna: '#8b5cf6',
  status: 'active',
  variables: [
    { key: 'nomor_spd',        label: 'Nomor SPD',             type: 'text',    required: true,  source: 'auto'   },
    { key: 'ppk',              label: 'Pejabat Pembuat Komitmen', type: 'pegawai', required: true,  source: 'pegawai', readonly: true },
    { key: 'pegawai',          label: 'Pegawai Pelaksana',     type: 'pegawai', required: true,  source: 'linked',  readonly: true },
    { key: 'tingkat_biaya',    label: 'Tingkat Biaya Perjalanan', type: 'text', required: true, source: 'input', default: 'Tingkat C' },
    { key: 'maksud',           label: 'Maksud Perjalanan Dinas', type: 'textarea',required: true,  source: 'linked' },
    { key: 'alat_angkut',      label: 'Alat Angkut Yang Digunakan', type: 'select', options: ['Kendaraan', 'Pesawat, Kendaraan'], required: true,  source: 'input', default: 'Kendaraan' },
    { key: 'berangkat_dari',   label: 'Berangkat Dari',        type: 'text',    required: true,  source: 'input' },
    { key: 'tempat_tujuan',    label: 'Tempat Tujuan',         type: 'text',    required: true,  source: 'linked' },
    { key: 'tanggal_berangkat',label: 'Tanggal Berangkat',     type: 'date',    required: true,  source: 'linked' },
    { key: 'tanggal_kembali',  label: 'Tanggal Harus Kembali', type: 'date',    required: true,  source: 'linked' },
    { key: 'akun',             label: 'Pembebanan Anggaran (Akun)', type: 'mak', required: true, source: 'input' },
    { key: 'tempat_dikeluarkan',label: 'Dikeluarkan di',       type: 'text',    required: true,  source: 'input', default: 'Singaraja' },
    { key: 'tanggal_dikeluarkan',label: 'Tanggal Dikeluarkan', type: 'date',    required: true,  source: 'input' },
  ],
  connections: [
    {
      targetSuratId: 'spby',
      type: 'requires',
      label: 'Diperlukan SPBY',
      variableMapping: {
        nomor_spd:         'nomor_spd_ref',
        pegawai:           'pegawai_list',
        tanggal_berangkat: 'tanggal_mulai',
        tanggal_kembali:   'tanggal_selesai',
        tujuan:            'tujuan',
      },
    },
  ],
  nodePosition: { x: 310, y: 220 },
};
